[package]
name = "pookie_db"
version = "0.1.0"
edition = "2021"

[dependencies]
flate2 = "1.0"
serde = { version = "1.0", features = ["derive"] }
rmp-serde = "1.1"
uuid = { version = "1.4", features = ["v4"] }
tokio = { version = "1.32.0", features = ["full"] }
rand = "0.8"
